"""Agregar campos ubicacion_tipo y ubicacion_grupo a Producto

Revision ID: 3aadec12439c
Revises: 44c67a1559f7
Create Date: 2025-05-14 12:18:29.141906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aadec12439c'
down_revision = '44c67a1559f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ubicacion_grupo', sa.String(length=100), nullable=True))
        batch_op.alter_column('tiene_descuento',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('valor_descuento',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('valor_descuento',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('tiene_descuento',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('ubicacion_grupo')
        batch_op.drop_column('ubicacion_tipo')

    # ### end Alembic commands ###
