"""Añadir nuevos campos para rastreo de descuentos

Revision ID: 44c67a1559f7
Revises: 3f15d0a7db6d
Create Date: 2025-05-11 01:03:45.058895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c67a1559f7'
down_revision = '3f15d0a7db6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen_descuento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('descuento_grupo_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fecha_aplicacion_descuento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('fecha_aplicacion_descuento')
        batch_op.drop_column('descuento_grupo_id')
        batch_op.drop_column('origen_descuento')

    # ### end Alembic commands ###
