"""init all tables

Revision ID: 9e40d6e8d87a
Revises: 
Create Date: 2025-04-15 17:21:11.135878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e40d6e8d87a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('url_imagen', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('codigos_disponibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('codigos_asignados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('viene_en_lotes', sa.Boolean(), nullable=True),
    sa.Column('num_lotes', sa.Integer(), nullable=True),
    sa.Column('mismo_stock_lotes', sa.Boolean(), nullable=True),
    sa.Column('stock_por_lote', sa.Integer(), nullable=True),
    sa.Column('unidad_lote', sa.String(length=50), nullable=True),
    sa.Column('usa_codigo_barras', sa.Boolean(), nullable=True),
    sa.Column('codigo_barras_externo', sa.String(length=100), nullable=True),
    sa.Column('codigo_interno', sa.String(length=100), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('tasa_impuesto', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('has_caducidad', sa.Boolean(), nullable=True),
    sa.Column('metodo_caducidad', sa.String(length=20), nullable=True),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('caducidad_lotes', sa.JSON(), nullable=True),
    sa.Column('caducidad_unidades', sa.JSON(), nullable=True),
    sa.Column('foto', sa.String(length=100), nullable=True),
    sa.Column('categoria_color', sa.String(length=7), nullable=True),
    sa.Column('url_imagen', sa.String(length=300), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('es_favorito', sa.Boolean(), nullable=True),
    sa.Column('esta_a_la_venta', sa.Boolean(), nullable=True),
    sa.Column('precio_cambia_frecuentemente', sa.Boolean(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('alerta_stock', sa.Integer(), nullable=True),
    sa.Column('divisa', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('codigos_asignados')
    op.drop_table('empresa')
    op.drop_table('codigos_disponibles')
    op.drop_table('catalogo_global')
    # ### end Alembic commands ###
