"""Añadir columna precio_final a tabla producto

Revision ID: e6b5f9a83575
Revises: 3aadec12439c
Create Date: 2025-05-21 20:57:06.569885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b5f9a83575'
down_revision = '3aadec12439c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        # MODIFICADO: Añadir server_default para evitar errores con registros existentes
        batch_op.add_column(sa.Column('precio_final', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('precio_final')
    # ### end Alembic commands ###